website/auth.py
from flask import Blueprint,request,flash, redirect, url_for, render_template
from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from wtforms import StringField,PasswordField,SubmitField,EmailField
from wtforms.validators import DataRequired
from .models import Users
from werkzeug.security import check_password_hash,generate_password_hash
from . import db
from flask_login import login_user,login_required,current_user,logout_user

auth = Blueprint('auth', __name__, template_folder='templates')

class SignupPage(FlaskForm):
    Profilepic = FileField("Profile Picture")
    First_name = StringField("First Name",validators=[DataRequired()])
    Surname = StringField("Surname", validators=[DataRequired()])
    Username = StringField("Username", validators=[DataRequired()])
    Email = EmailField("Email", validators=[DataRequired()])
    Password = PasswordField("Password",validators=[DataRequired()])
    Retype_password= PasswordField("Retype-Password", validators=[DataRequired()])
    Submit= SubmitField("Submit")

class LoginPage(FlaskForm):
    Username = StringField("Username", validators=[DataRequired()])
    Password = PasswordField("Password",validators=[DataRequired()])

    Submit= SubmitField("Login")

class ForgotPass(FlaskForm):
    Email = EmailField("Email", validators=[DataRequired()])
    Password = PasswordField("New Password", validators=[DataRequired()])
    Password2 = PasswordField("Retype Password", validators=[DataRequired()])

    Submit= SubmitField("Submit")

@auth.route("/signup",methods=["POST","GET"])
def signup():
    form = SignupPage()
    if request.method == "POST":
        First_name = form.First_name.data
        Surname = form.Surname.data
        Username = form.Username.data
        Email = form.Email.data
        Password = form.Password.data
        Retype_pasword = form.Retype_password.data

        user = Users.query.filter_by(username=Username).first()
        if user:
            flash("User already exists", category="error")
        elif len(First_name)< 2:
            flash("First_name too short", category="error")
        elif len(Username) < 2:
            flash("Username is Too short", category="error")
        elif len(Surname) <2:
            flash("Surname is too short", category="error")
        elif Password != Retype_pasword:
            flash("Passwords do not match", category="error")
        elif len(Email) < 6:
            flash("The email given is Invalid", category="error")
        else:
            new_user = Users(firstname=First_name,username=Username,password=generate_password_hash(Password,method="sha256"), surname=Surname,email=Email)
            db.session.add(new_user)
            db.session.commit()
            flash("Account Created Succesfully!!Now Log in", category="Success")
            login_user(new_user, remember=True)

            return redirect(url_for("auth.login"))

    return render_template("signup.jinja2", form=form, user=current_user)

@auth.route("/",methods=["POST","GET"])
def login():

    form = LoginPage()
    if request.method == 'POST':
        username = form.Username.data
        password = form.Password.data

        user = Users.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Login Successful", category="Success")
                login_user(user, remember=True)
                return redirect(url_for("views.bookpage"))
            else:
                flash("Incorrect Password! Try Again",category="error")
        else:
            flash("Username doesn't exist",category="error")
    return render_template("login.jinja2", form=form, user=current_user)

@auth.route("/reset", methods=["POST","GET"])
def reset():
    form = ForgotPass()
    if request.method == "POST":
        Email = form.Email.data
        Password = form.Password.data
        Password2 = form.Password2.data

        user = Users.query.filter_by(email=Email).first()
        if user :
            if Password == Password2:
                user.password = generate_password_hash(Password,method="sha256")
                flash("Password Reset Successfull", category="Success")
                db.session.commit()
                return redirect(url_for("auth.login"))
            else:
                flash("Passwords Do Not Match!!Try Again",category="Error")

        else:
            flash("Email Does Not Exist!Try Again", category="Error")

    return render_template("forgot.jinja2", form=form, user=current_user)

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You have logged out", category="Success")
    return redirect(url_for("auth.login"))

website/views.py
import uuid
import os
from .forms import Bookpage,Search,UpdateUser,UpdateBook
from flask import Blueprint,render_template,flash,request,redirect,url_for
from .models import Books,Users
from . import db
from flask_login import login_required,current_user
from werkzeug.utils import secure_filename



UPLOAD_FOLDER = 'website/static/images/'

views = Blueprint('views',__name__,static_folder='static', template_folder='templates')

@views.route("/bookpage", methods=["GET", "POST"])
@login_required
def bookpage():
    form = Bookpage()
    if request.method == 'POST':
        name = form.Bookname.data
        author = form.Author.data
        about = form.About.data

        book = Books.query.filter_by(name=name).first()
        if book:
            flash("Book is already added", category="Error")
        elif len(author) < 2:
            flash("Author Name is Too Short",category="Error")
        elif len(name) < 2:
            flash("Book Name is Too Short", category="Error")
        else:
            new_book = Books(name=name, author=author, about=about, user_id=current_user.id)
            db.session.add(new_book)
            db.session.commit()

            flash("Book added successfully!You can now read", category="Success")
            return redirect(url_for('views.allbooks'))
    return render_template("bookpage.jinja2", form=form, user=current_user)

@views.route("/dashboard/<int:id>", methods=["POST","GET"])
@login_required
def dashboard(id):
    form = UpdateUser()
    user = Users.query.get(id)
    if request.method == "POST":
        user.username = form.Username.data
        user.firstname = form.Firstname.data
        user.surname = form.Surname.data
        user.email = form.Email.data
        user.profpic = form.Profile_pic.data

        #grab pic
        pic = secure_filename(user.profpic.filename)
        #set uuid
        pic_name = str(uuid.uuid4()) + "_" + pic

        #change to string
        user.profpic = pic_name
        # save image
        saver = form.Profile_pic.data
        try:
            flash("Profile updated successfully", category="Success")
            db.session.commit()
            saver.save(os.path.join(UPLOAD_FOLDER, pic_name))
            return render_template("dashboard.jinja2", user=current_user, form=form)
        except:
            flash("Invalid user",category="Error")
    else:
        return render_template("dashboard.jinja2", user=current_user, form=form)
    return render_template("dashboard.jinja2", user=current_user, form=form)

@views.context_processor
def search():
    form = Search()
    return dict(form=form)

@views.route("/search", methods=["POST"])
def search():
    form = Search()
    if request.method == "POST":
         searched = form.Search.data
         books = Books.query.filter(Books.name.like('%'+searched+'%'))
         return render_template('search.jinja2', form=form, books=books,user=current_user)

@views.route("/books")
@login_required
def allbooks():
    all_books = Books.query.order_by(Books.date_added)
    return render_template('books.jinja2', user = current_user,books=all_books)

@views.route("/delete_user")
@login_required
def users():
    users = Users.query.order_by(Users.date_added)
    return render_template('delete_users.jinja2', user=current_user,users=users)

@views.route("/delete_user/<int:id>")
@login_required
def delete_users(id):
    delete_user = Users.query.get(id)
    db.session.delete(delete_user)
    db.session.commit()
    flash("User Deleted Successfully", category="Success")
    return render_template('delete_users.jinja2', user=current_user, delete_user=delete_user)

@views.route("/update_book/<int:id>",methods=["POST","GET"])
@login_required
def update_book(id):
    book_to_update = Books.query.get(id)
    form = UpdateBook()
    if request.method == "POST":
        book_to_update.name = form.Bookname.data
        book_to_update.author = form.Author.data
        book_to_update.read = form.Read.data
        book_to_update.about = form.About.data
        book_to_update.book_pic = form.Pic.data
        try:
            bookpicName= secure_filename(book_to_update.book_pic.filename)
            bookName = bookpicName+'_'+str(uuid.uuid4())

            book_to_update.book_pic = bookName
            saver = form.Pic.data

            try:
                flash("Book details updated successfully", category="Success")
                db.session.commit()
                saver.save(os.path.join(UPLOAD_FOLDER, bookName))
                return render_template("update_books.jinja2", user=current_user, form=form, book=book_to_update)
            except:
                flash("Invalid user",category="Error")
        except:
            flash("Please update even the picture", category="Error")
            return render_template("update_books.jinja2", user=current_user, form=form,book=book_to_update)
    return render_template("update_books.jinja2", user=current_user, form=form, book=book_to_update)

@views.route("/delete/<int:id>")
@login_required
def delete_book(id):
    book_to_delete = Books.query.get(id)
    db.session.delete(book_to_delete)
    db.session.commit()
    all_books = Books.query.order_by(Books.date_added)
    flash("Book has been deleted",category="Success")
    return render_template('books.jinja2', user = current_user,books=all_books)

website/templates/404.jinja2
<br/>
<center>
<h1> 404 error </h1>
<p> Page Not Found </p>
</center>

website/templates/500.jinja2
<br/>
<center>
<h1> 500 error </h1>
<p> Server Error </p>
</center>

website/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Book Tracker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="{{url_for('static', filename='css/styles.css')}}" rel="stylesheet">
    <link rel="shortcut icon" href="https://robohash.org/2600:6c5e:357f:e274:dd4:78bb:b35f:924d.png">
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </symbol>
      <symbol id="info-fill" viewBox="0 0 16 16">
        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
      </symbol>
      <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </symbol>
    </svg>
  </head>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Fratbooks</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    {% if user.is_authenticated and user.id ==4 %}
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('views.dashboard', id=user.id)}}">User Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('views.bookpage')}}">Add Book</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('views.allbooks')}}">See Added Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('views.users')}}">Delete Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('auth.logout')}}">Logout</a>
        </li>
      </ul>
      <form class="d-flex" role="search" name="search" method="POST" action="{{url_for('views.search')}}">
        {{form.hidden_tag()}}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit">Search</button>
      </form>
    {% elif user.is_authenticated and user.id != 4%}
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('views.dashboard', id=user.id)}}">User Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('views.bookpage')}}">Add Book</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('views.allbooks')}}">See Added Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#">See Suggested Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('auth.logout')}}">Logout</a>
        </li>
      </ul>
      <form class="d-flex" role="search" name="search" method="POST" action="{{url_for('views.search')}}">
        {{form.hidden_tag()}}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit">Search</button>
      </form>
    {% else %}
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('auth.login')}}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('auth.signup')}}">Sign Up</a>
        </li>
      </ul>
    {% endif %}
    </div>
  </div>
</nav>
  <br/>
  <body>
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages%}
      {% for category,message in messages%}
        {% if category == 'Success'%}
        <div class="container-fluid">
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="20" height="20" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
              <div>
                {{ message }}
              </div>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% else %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <svg class="bi flex-shrink-0 me-2" width="20" height="20" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
              <div>
                {{message}}
              </div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        </div>
        {%endif%}
      {% endfor %}
    {% endif %}
    {% endwith%}
    <div class="container-fluid">
      {% block content%}
      {% endblock %}
    </div>
    <script src="https://cdn.ckeditor.com/4.10.0/standard/ckeditor.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
  </body>
</html>

website/templates/bookpage.jinja2
{% extends 'base.html' %}
{% block content%}
    <h3 align="center"> Add New Book </h3>
    <br/><br/>
    <div class="container-fluid">
        <form method= "POST" enctype="multipart/form-data>
        {{ form.hidden_tag() }}
        {{ form.Bookname.label (class="form-label", id="label")}}
        {{ form.Bookname(class="form-control") }}
        {{ form.Author.label (class="form-label", id="label")}}
        {{ form.Author(class="form-control") }}
        {{ form.About.label (class="form-label", id="label")}}
        {{ form.About(class="form-control") }}
        </br>
        {{ form.Submit(class="btn btn-dark mb-3") }}
    </div>
                    {{ ckeditor.load(pkg_type="basic")}}
                    {{ ckeditor.config(name='About')}}
{% endblock %}

website/templates/books.jinja2
{% extends 'base.html' %}
{% block content%}
    <h3 align="center"> BOOKS ADDED </h3>
    <br/><br/>
    {% for book in books %}
    <div class="container-fluid">
        <div class="card mb-3" style="max-width: 540px;">
          <div class="row g-0">
            <div class="col-md-4">
            {% if book.book_pic %}
              <img src="{{url_for('static',filename=('images/'+book.book_pic))}}" class="img-fluid rounded-start" alt="...">
            {% else %}
              <img src="{{url_for('static',filename=('images/photo.jpeg'))}}" class="img-fluid rounded-start" alt="...">
            {% endif%}
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">Book Name: {{book.name}}</h5>
                <p class="card-text">Book About: {{book.about}}</p>
                <p class="card-text"><small class="text-muted">Book Author: {{book.author}}</small></p>
                <p class="card-text"><small class="text-muted">Is the book read: {{book.read}}</small></p>
                <p class="card-text"><small class="text-muted">Date Added: {{book.date_added}}</small></p>
              </div>
                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                    <a href="{{url_for('views.update_book', id=book.id)}}">
                      <button type="button" class="btn btn-dark">Update</button>
                    </a>
                    <a href="{{url_for('views.delete_book', id=book.id)}}">
                      <button type="button" class="btn btn-danger">Delete</button>
                    </a>
                </div>
            </div>
          </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

website/templates/dashboard.jinja2
{% extends 'base.html' %}
{% block content%}
    <center><h2>{{user.username}}'s Dashboard</h2></center>
    <br/><br/>
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row g-0">
        <div class="col-md-4">
                {% if user.profpic %}
            <img src="{{url_for('static', filename=('images/'+user.profpic))}}" class="img-fluid rounded-start" alt="...">
                {% else %}
          <img src="{{url_for('static', filename=('images/profile_picture.png'))}}" class="img-fluid rounded-start" alt="...">
                {% endif %}
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">My Details</h5>
            <p class="card-text"><small><strong>Userame: </strong>{{user.username}}</small></p>
            <p class="card-text"><small><strong>Email: </strong>{{user.email}}</small></p>
            <p class="card-text"><small><strong>First Name: </strong>{{user.firstname}}</small></p>
            <p class="card-text"><small><strong>Surname: </strong>{{user.surname}}</small></p>
            <p class="card-text"><small><strong>Date joined: </strong>{{user.date_added}}</small></p>
          </div>
        </div>
      </div>
    </div>
    <br/><br/>
    <form method = 'POST' enctype='multipart/form-data'>
      <div class="container-fluid">
        <div class="card w-50">
          <div class="card-body">
            <h5 class="card-title">Update Form</h5>
                {{ form.hidden_tag() }}
                {{ form.Username.label (class="form-label", id="label")}}
                {{ form.Username(class="form-control", value=user.username) }}
                {{ form.Firstname.label (class="form-label", id="label")}}
                {{ form.Firstname(class="form-control",value=user.firstname) }}
                {{ form.Surname.label (class="form-label", id="label")}}
                {{ form.Surname(class="form-control",value=user.surname) }}
                {{ form.Email.label (class="form-label", id="label")}}
                {{ form.Email(class="form-control",value=user.email) }}
                {{ form.Profile_pic.label (class="form-label", id="label")}}
                {{ form.Profile_pic(class="form-control, value=user.profpic") }}
                <br/>
                {{form.Submit(class="btn btn-dark mb-3")}}
          </div>
        </div>
      </div>
    </form>

{% endblock %}

website/templates/delete_users.jinja2
{% extends 'base.html' %}
{% block content%}
    <h3> Delete Users </h3>
     {% for user in users %}
    <div class="container-fluid">
        <div class="card mb-3" style="max-width: 540px;">
          <div class="row g-0">
            <div class="col-md-4">
            {% if user.profpic %}
              <img src="{{url_for('static',filename=('images/'+user.profpic))}}" class="img-fluid rounded-start" alt="...">
            {% else %}
              <img src="{{url_for('static',filename=('images/profile_picture.png'))}}" class="img-fluid rounded-start" alt="...">
            {% endif%}
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{user.username}}</h5>
                <p class="card-text">{{user.email}}</p>
                <p class="card-text"><small class="text-muted">{{user.date_added}}</small></p>
              </div>
            </div>
                <a href="{{url_for('views.delete_users', id=user.id)}}">
                  <button type="button" class="btn btn-danger">Delete</button>
                </a>
            </div>
          </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

website/templates/forgot.jinja2
{% extends 'base.html' %}
{% block content%}
    <h3 align="center"> Reset Password </h3>
    <br/><br/>
    <div class="container-fluid">
        <form method= "POST">
        {{ form.hidden_tag() }}
        {{ form.Email.label (class="form-label", id="label")}}
        {{ form.Email(class="form-control") }}
        {{ form.Password.label (class="form-label", id="label")}}
        {{ form.Password(class="form-control") }}
        {{ form.Password2.label (class="form-label", id="label")}}
        {{ form.Password2(class="form-control") }}
        </br>
        {{ form.Submit(class="btn btn-dark mb-3") }}
    </div>
{% endblock %}

website/templates/home.jinja2
{% extends 'base.html' %}
{% block content%}

{% if Email %}
    <h1> {{Email}} </h1>
{% else %}
    <form method= "POST">
    {{ form.hidden_tag() }}
    {{ form.Email.label (class="form-label", id="label")}}
    {{ form.Email(class="form-control") }}
    </br>
    {{ form.Submit(class="btn btn-dark mb-3") }}

{% endif %}
{% endblock %}

website/templates/login.jinja2
{% extends 'base.html' %}
{% block content%}
    <h3 align="center"> Welcome!To The Book App. </h3>
    <br/><br/>
    <div class="container-fluid">
        <form method= "POST">
        {{ form.hidden_tag() }}
        {{ form.Username.label (class="form-label", id="label")}}
        {{ form.Username(class="form-control") }}
        {{ form.Password.label (class="form-label", id="label")}}
        {{ form.Password(class="form-control") }}
        </br>
        {{ form.Submit(class="btn btn-dark mb-3") }}
        </br>
        <ul>
            <li><a href={{url_for('auth.reset')}} id="demo">Forgot Your Password</a></li>
            <li><a href={{url_for('auth.signup')}} id="demo2"> Create Account</a></li>
        </ul>
    </div>
{% endblock %}

website/templates/search.jinja2
{% extends 'base.html'%}

{% block content %}
<h3> Search Results </h3>
{% for book in (books, suggestions) %}
{% if book %}

<div class="card">
  <img src="..." class="card-img-top" alt="...">

  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

<div class="card" aria-hidden="true">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title placeholder-glow">
      <span class="placeholder col-6"></span>
    </h5>
    <p class="card-text placeholder-glow">
      <span class="placeholder col-7"></span>
      <span class="placeholder col-4"></span>
      <span class="placeholder col-4"></span>
      <span class="placeholder col-6"></span>
      <span class="placeholder col-8"></span>
    </p>
    <a href="#" tabindex="-1" class="btn btn-primary disabled placeholder col-6"></a>
  </div>
</div>
{% endif %}
{% endfor %}
{% endblock%}

website/templates/signup.jinja2
{% extends 'base.html' %}
{% block content%}
    <h3 align="center"> Sign Up </h3>
    <br/><br/>
    <div class="container-fluid">
        <form method= "POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ form.Username.label (class="form-label", id="label")}}
        {{ form.Username(class="form-control") }}
        {{ form.First_name.label (class="form-label", id="label")}}
        {{ form.First_name(class="form-control") }}
        {{ form.Surname.label (class="form-label", id="label")}}
        {{ form.Surname(class="form-control") }}
        {{ form.Email.label (class="form-label", id="label")}}
        {{ form.Email(class="form-control") }}
        {{ form.Password.label (class="form-label", id="label")}}
        {{ form.Password(class="form-control") }}
        {{ form.Retype_password.label (class="form-label", id="label")}}
        {{ form.Retype_password(class="form-control") }}
        </br>
        {{ form.Submit(class="btn btn-dark mb-3") }}
    </div>
{% endblock %}

website/templates/update_books.jinja2
{% extends 'base.html' %}
{% block content%}
<form method = 'POST' enctype='multipart/form-data'>
      <div class="container-fluid">
        <div class="card w-100">
          <div class="card-body">
            <h5 class="card-title">Update Form</h5>
                {{ form.hidden_tag() }}
                {{ form.Bookname.label (class="form-label", id="label")}}
                {{ form.Bookname(class="form-control", value=book.name) }}
                {{ form.Author.label (class="form-label", id="label")}}
                {{ form.Author(class="form-control",value=book.author) }}
                {{ form.About.label (class="form-label", id="label")}}
                {{ form.About(class="form-control",value=book.about) }}
                {{ form.Pic.label (class="form-label", id="label")}}
                {{ form.Pic(class="form-control, value=book.pic") }}
                <div class="field">
                {{ form.Read(form='updatebook') }}
                {{ form.Read.label}}
                </div>
                <br/>
                {{form.Submit(class="btn btn-dark mb-3")}}
          </div>
        </div>
      </div>
    </form>

{% endblock %}